# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notidb < Formula
  desc ""
  homepage "https://github.com/ChmaraX/notidb"
  version "0.0.1"

  on_macos do
    url "https://github.com/ChmaraX/notidb/releases/download/v0.0.1/notidb_0.0.1_darwin_all.tar.gz"
    sha256 "cbb8f018766cf33198d5706b131a74a61e740e7cf3977d8a41f482523b21b059"

    def install
      bin.install "notidb"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChmaraX/notidb/releases/download/v0.0.1/notidb_0.0.1_linux_arm64.tar.gz"
      sha256 "dc80ed43d18c6e1dc2e82548a2732a6640da774821489ee69bcf726030d94018"

      def install
        bin.install "notidb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ChmaraX/notidb/releases/download/v0.0.1/notidb_0.0.1_linux_amd64.tar.gz"
      sha256 "9c853c3d8e76334a2a84c709f36ca1932908adc24004913f57557f2120ba6890"

      def install
        bin.install "notidb"
      end
    end
  end
end
